/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login user */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest']
        }
      }
      responses: {
        /** @description Login successful */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AuthResponse']
          }
        }
        401: components['responses']['UnauthorizedError']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Register new user */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['RegisterRequest']
        }
      }
      responses: {
        /** @description Registration successful */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AuthResponse']
          }
        }
        400: components['responses']['BadRequestError']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh access token */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: {
          refreshToken?: string
        }
      }
      requestBody?: never
      responses: {
        /** @description Access token refreshed successfully */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AuthResponse']
          }
        }
        401: components['responses']['UnauthorizedError']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/habits': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all habits */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of habits */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['HabitDefinition'][]
          }
        }
        401: components['responses']['UnauthorizedError']
      }
    }
    put?: never
    /** Create a new habit */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateHabitRequest']
        }
      }
      responses: {
        /** @description Habit created successfully */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['HabitDefinition']
          }
        }
        400: components['responses']['BadRequestError']
        401: components['responses']['UnauthorizedError']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/habits/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete a habit */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          key: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Habit deleted successfully */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        401: components['responses']['UnauthorizedError']
        404: components['responses']['NotFoundError']
      }
    }
    options?: never
    head?: never
    /** Rename a habit */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          key: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateHabitRequest']
        }
      }
      responses: {
        /** @description Habit updated successfully */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['HabitDefinition']
          }
        }
        400: components['responses']['BadRequestError']
        401: components['responses']['UnauthorizedError']
        404: components['responses']['NotFoundError']
      }
    }
    trace?: never
  }
  '/sleep-records': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all sleep records */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of all sleep records */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['DailyEntry'][]
          }
        }
        401: components['responses']['UnauthorizedError']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sleep-records/{date}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get sleep record by date */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          date: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Sleep record found */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['DailyEntry']
          }
        }
        401: components['responses']['UnauthorizedError']
        404: components['responses']['NotFoundError']
      }
    }
    /** Create or update sleep record for a day */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          date: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SleepDataInput']
        }
      }
      responses: {
        /** @description Sleep record updated successfully */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['DailyEntry']
          }
        }
        400: components['responses']['BadRequestError']
        401: components['responses']['UnauthorizedError']
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sleep-records/{date}/habits/{habitKey}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove habit from a specific day */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          date: string
          habitKey: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Habit removed successfully */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['DailyEntry']
          }
        }
        401: components['responses']['UnauthorizedError']
        404: components['responses']['NotFoundError']
      }
    }
    options?: never
    head?: never
    /** Update habit value for a specific day */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          date: string
          habitKey: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateHabitValueRequest']
        }
      }
      responses: {
        /** @description Habit value updated successfully */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['DailyEntry']
          }
        }
        400: components['responses']['BadRequestError']
        401: components['responses']['UnauthorizedError']
        404: components['responses']['NotFoundError']
      }
    }
    trace?: never
  }
  '/sleep-records/yesterday/check': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Check if yesterday's sleep data exists */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Check result */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CheckYesterdayResponse']
          }
        }
        401: components['responses']['UnauthorizedError']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sleep-stats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get sleep statistics */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Sleep statistics */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SleepStatsResponse']
          }
        }
        401: components['responses']['UnauthorizedError']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    LoginRequest: {
      /** Format: email */
      email: string
      /** Format: password */
      password: string
    }
    User: {
      id: string
      /** Format: email */
      email: string
    }
    AuthResponse: {
      accessToken: string
      user: components['schemas']['User']
    }
    Error: {
      message: string
      code: string
    }
    RegisterRequest: {
      /** Format: email */
      email: string
      /** Format: password */
      password: string
    }
    HabitDefinition: {
      key: string
      label: string
      /** Format: date-time */
      createdAt: string
    }
    CreateHabitRequest: {
      label: string
    }
    UpdateHabitRequest: {
      label: string
    }
    SleepData: {
      bedtime: string | null
      wakeTime: string | null
      napDuration: number | null
      duration: number | null
    }
    HabitCheck: {
      key: string
      value: boolean
    }
    DailyEntry: {
      id: string
      date: string
      sleep: components['schemas']['SleepData']
      habits: components['schemas']['HabitCheck'][]
    }
    SleepDataInput: {
      bedtime: string | null
      wakeTime: string | null
      napDuration: number | null
    }
    UpdateHabitValueRequest: {
      value: boolean
    }
    CheckYesterdayResponse: {
      hasData: boolean
    }
    SleepStatsPeriod: {
      bedtime: string | null
      wakeTime: string | null
      duration: string | null
    }
    SleepStatsResponse: {
      week: components['schemas']['SleepStatsPeriod']
      month: components['schemas']['SleepStatsPeriod']
      year: components['schemas']['SleepStatsPeriod']
    }
  }
  responses: {
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Bad request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Resource not found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
