openapi: 3.0.0
info:
  title: Sadhana Tracker API
  description: Sadhana Tracker API
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:

  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"

  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/register" 

  /auth/refresh:
    post:
      $ref: "./endpoints/auth.yaml#/refresh"
